---
###############################################################
# This playbook installs Docker and an Apache Web Server and
# opens ports on the firewall
###############################################################

- name: Install and manage one or more Apache Web Server(s)
  hosts: all
  become: yes
  tasks:
    - name: Configure /etc/resolv.conf
      include_role:
        name: resolv.conf
      tags:
        - configure_resolv_conf
    - name: Open port 80 as needed for the Apache Web Server
      include_role:
        name: firewalld
    - name: Install Apache
      include_role:
        name: apache-web-server
      tags:
        - install_apache